import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen w-full">
          <NavBar />
          {children}
          {/* <Footer /> */}
        </div>
      </body>
    </html>
  )
}

function NavBar() {
  return (
    <div className="grid grid-cols-[1fr_auto_1fr] gap-4 p-8">
      <div className="flex gap-6 items-center">
        <div className="flex gap-2 items-center">
          <div className="size-6 bg-white rounded-full"></div>
          <p className="font-mono uppercase">Thomas Inc</p>
        </div>
        {['all', 'shirts', 'stickers'].map((item) => (
          <Link
            key={item}
            href={`/${item}`}
            className="text-zinc-500 hover:text-zinc-400 active:scale-95 duration-300 font-mono text-sm"
          >
            {item}
          </Link>
        ))}
      </div>
      <input
        className="border border-zinc-800 rounded-lg px-3 outline-none focus:border-zinc-400 focus:border-dashed py-2 w-full bg-transparent duration-300 placeholder:text-zinc-500"
        placeholder="Search..."
      />
    </div>
  )
}

function Footer() {}
